version: '3.4'

services:
  goodbooks.api:
    image: ${DOCKER_REGISTRY-}goodbooksapi
    build:
      context: .
      dockerfile: GoodBooks.Api/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    expose:
      - 8000
      - 8001
    depends_on:
      - db
      - elasticsearch 
  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "23-HJkX3mt"
    ports:
      - '14330:1433'
    expose:
      - 14330
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local